version: '3.8'

services:
  app:
    image: asmmp:latest
    environment:
      - REDIS_URL=redis://:password123@redis:6379
      - NODE_ENV=development
      - OPENAI_API_KEY=dummy-key
      - DISABLE_PLATFORM_INIT=true
      - DISABLE_TWITTER=true
      - DISABLE_TELEGRAM=true
      - DISABLE_DISCORD=true
    ports:
      - '3000:3000'
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    command: redis-server --requirepass password123 --protected-mode no
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'password123', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redis-insight:/db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  redis_data:
  redis-insight:
  prometheus_data:
  grafana_data:
