version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=dummy-key
      - DISABLE_PLATFORM_INIT=true
      - DISABLE_TWITTER=true
      - DISABLE_TELEGRAM=true
      - DISABLE_DISCORD=true
    depends_on:
      redis:
        condition: service_healthy
      prometheus:
        condition: service_started

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
