apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: asmmp
data:
  redis.conf: |
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    appendonly no
    save 900 1
    save 300 10
    save 60 10000
    databases 1
    tcp-keepalive 60
    timeout 300
    loglevel warning
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asmmp-config
  namespace: asmmp
data:
  NODE_ENV: "production"
  LOG_LEVEL: "debug"
  REDIS_URL: "redis://redis:6379"
  CONTENT_GENERATION_INTERVAL: "3600"
  MAX_POSTS_PER_DAY: "10"
  DISABLE_PLATFORM_INIT: "true"
  DISABLE_TELEGRAM: "true"
  DISABLE_TWITTER: "true"
  DISABLE_DISCORD: "true" 