apiVersion: apps/v1
kind: Deployment
metadata:
  name: asmmp
  namespace: asmmp
  labels:
    app: asmmp
    app.kubernetes.io/name: asmmp
    app.kubernetes.io/part-of: social-media-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asmmp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: asmmp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: asmmp
          image: asmmp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: asmmp-config
            - secretRef:
                name: asmmp-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          volumeMounts:
            - name: redis-config
              mountPath: /app/config/redis
            - name: app-data
              mountPath: /app/data
            - name: app-logs
              mountPath: /app/logs
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: app-data
          persistentVolumeClaim:
            claimName: asmmp-data
        - name: app-logs
          persistentVolumeClaim:
            claimName: asmmp-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asmmp-data
  namespace: asmmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: asmmp-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asmmp-logs
  namespace: asmmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: asmmp-logs-pv
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asmmp-hpa
  namespace: asmmp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asmmp
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 