name: Repository Settings

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/repo-settings.yml'

permissions:
  contents: read
  actions: write
  security-events: write
  pull-requests: write
  issues: write

jobs:
  configure-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Repository Settings
        uses: repository-settings/action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          has_wiki: false
          has_projects: true
          allow_squash_merge: true
          allow_merge_commit: false
          allow_rebase_merge: true
          delete_branch_on_merge: true
          enable_automated_security_fixes: true
          enable_vulnerability_alerts: true
          security:
            enable_vulnerability_alerts: true
            enable_automated_security_fixes: true
            enable_dependency_graph: true
          branch_protection:
            main:
              required_status_checks:
                strict: true
                contexts:
                  - "test"
                  - "build-and-push"
              enforce_admins: false
              required_pull_request_reviews:
                required_approving_review_count: 1
                dismiss_stale_reviews: true
                require_code_owner_reviews: true
                require_last_push_approval: true
                dismissal_restrictions:
                  users: []
                  teams: []
              restrictions: null
              required_linear_history: true
              allow_force_pushes: false
              allow_deletions: false
              required_conversation_resolution: true
              lock_branch: true 